CREATE DATABASE alx_book_store;
USE alx_book_store;

CREATE TABLE Authors (
   AUTHOR_ID INT PRIMARY KEY,
   AUTHOR_NAME VARCHAR(215)
);
CREATE TABLE Books (
    BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(130),
    AUTHOR_ID INT,
    PRICE DOUBLE ,
    publication_date DATE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES Authors(AUTHOR_ID)
);

CREATE TABLE Customers (
   Customer_ID INT PRIMARY KEY,
   CUSTOMER_NAME VARCHAR(215),
   EMAIL VARCHAR(215),
   ADDRESS TEXT
);
CREATE TABLE Orders (
   ORDER_ID INT PRIMARY KEY,
   Customer_ID INT,
   ORDER_DATE DATE,
   FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);
CREATE TABLE Order_Details (
   orderdetailid  INT PRIMARY KEY,
   ORDER_ID INT,
   BOOK_ID INT,
   QUANTITY DOUBLE,
   FOREIGN KEY (ORDER_ID) REFERENCES Orders(ORDER_ID),
   FOREIGN KEY (BOOK_ID) REFERENCES Books(BOOK_ID)
);