CREATE DATABASE Alx_Book_Store IF NOT EXISTS;
USE Alx_Book_Store;
CREATE TABLE Books (
    BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(130),
    AUTHOR_ID,
    PRICE DOUBLE ,
    PUBLISHED_DATE DATE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES Authors(AUTHOR_ID)
);
CREATE TABLE Authors (
   AUTHOR_ID INT PRIMARY KEY,
   AUTHOR_NAME VARCHAR(215)
);
CREATE TABLE Customers (
   Customer_ID INT PRIMARY KEY,
   CUSTOMER_NAME VARCHAR(215),
   EMAIL VARCHAR(215),
   ADDRESS TEXT
);
CREATE TABLE Orders (
   ORDER_ID INT PRIMARY KEY,
   CUSTOMER_ID INT,
   ORDER_DATE DATE,
   FOREIGN KEY (CUSTOMER_ID) REFERENCES Customers(CUSTOMER_ID)
);
CREATE TABLE Order_Details (
   orderdetailid  INT PRIMARY KEY,
   ORDER_ID INT,
   BOOK_ID INT,
   QUANTITY DOUBLE,
   FOREIGN KEY (ORDER_ID) REFERENCES Orders(ORDER_ID),
   FOREIGN KEY (BOOK_ID) REFERENCES Books(BOOK_ID)
);